git-hooks.plugin.id=${gitHooksPluginId}
git-hooks.plugin.version=${gitHooksPluginVersion}
git-hooks.cache.root=${gitHooksCacheRoot}
git-hooks-setup.plugin.id=${setupPluginId}
git-hooks-setup.plugin.version=${setupPluginVersion}
git-hooks-setup.markerPath=${setupMarkerPath}
